SET ROLE = 'hut-finder';
BEGIN;

UPDATE hut
SET category = 4
WHERE name IN (
               'Ahuriri Base Hut',
               'Albert Burn Hut',
               'Alfred Hut',
               'Alice Nash Memorial Heritage Lodge',
               'Alpha Hut',
               'Anatoki Forks Hut',
               'Anderson Memorial Hut',
               'Anti Crow Hut',
               'Aparima Hut',
               'Architect Creek Hut',
               'Arete Forks Hut',
               'Atiwhakatu Hut',
               'Avoca Homestead',
               'Awapoto Hut',
               'Back Ridge Hut',
               'Ball Hut',
               'Ballard Hut',
               'Barbers Hut',
               'Barlow Hut',
               'Basins Hut',
               'Beebys Hut',
               'Begley Hut',
               'Belltown Manunui Hut',
               'Big Bay Hut',
               'Big Hellfire Hut',
               'Big Hut',
               'Black Hill Hut',
               'Blowfly Hut',
               'Blue Mountain Hut',
               'Blue Range Hut',
               'Bluff Hut',
               'Bobs Hut',
               'Bog Inn Hut',
               'Bottom Gordon Hut',
               'Bottom Misery Hut',
               'Boulder Forks Hut',
               'Boulder Lake Hut',
               'Boundary Creek Hut',
               'Boundary Hut',
               'Branch Creek Hut',
               'Brodrick Hut',
               'Browning Hut',
               'Buckland Peak Hut',
               'Bullendale Hut',
               'Bungaree Hut',
               'Bush Hut',
               'Butler Junction Hut',
               'Cameron Hut',
               'Cameron Hut',
               'Captains Creek Hut',
               'Careys Hut',
               'Carkeek Hut',
               'Carroll Hut',
               'Cascade Hut',
               'Cassel Flat Hut',
               'Castle Rock Hut',
               'Castle Rocks Hut',
               'Cattle Creek Hut',
               'Cattle Ridge Hut',
               'Caves Hut',
               'Cedar Flat Hut',
               'Central Te Hoe Hut',
               'Central Waiau Hut',
               'Cheviot Downs Hut',
               'Christmas Flat Hut',
               'Christmas Village Hut',
               'Cold Stream Hut',
               'Coldwater Hut',
               'Colenso Hut',
               'Connors Creek Hut',
               'Coppermine Creek Hut',
               'Cotters Hut',
               'Cow Creek Hut',
               'Crow Hut',
               'Crow Hut',
               'Crow Hut',
               'Cullers Hut',
               'Cupola Hut',
               'Curtis Memorial Hut',
               'D''Urville Hut',
               'Daly''s Clearing Hut',
               'Daphne Hut',
               'Dead Dog Hut',
               'Deas Cove Hut',
               'Devils Creek Hut',
               'Dillon Hut',
               'Dodger Hut',
               'Dorset Ridge Hut',
               'Doubtless Hut',
               'Doughboy Bay Hut',
               'Douglas Rock Hut',
               'Dundas Hut',
               'Dynamo Hut',
               'East Matakitaki Hut',
               'East Ruggedy Hut',
               'Elcho Hut',
               'Elder Hut',
               'Elizabeth Hut',
               'Ellis Hut',
               'Ferguson Hut',
               'Fern Burn Hut',
               'Field Hut',
               'Fishtail Hut',
               'Flanagans Hut',
               'Forbes Hut',
               'Forbes Hut (previously Seymour Hut)',
               'Forks Hut',
               'Fosters Hut',
               'Frampton''s Hut',
               'Freds Camp Hut',
               'Freeman Burn Hut',
               'Freshwater Hut',
               'Frew Hut',
               'George Lyon Hut',
               'George Sound Hut',
               'Glaisnock Hut',
               'Glengyle Hut',
               'Goat Pass Hut',
               'Godley Hut',
               'Gorge River Hut',
               'Granity Pass Hut',
               'Grassy Flat Hut',
               'Green Lake Hut',
               'Greigs Hut',
               'Growler Hut',
               'Hacket Hut',
               'Hagens Hut',
               'Halfway Hut',
               'Hanamahihi Hut',
               'Hapuku Hut',
               'Harkness Hut',
               'Harman Hut',
               'Hauhungaroa Hut',
               'Hauroko Burn Hut',
               'Helicopter Flat Hut',
               'Herepai Hut',
               'Hidden Hut',
               'Highland Creek Hut',
               'Hinerua Hut',
               'Hoka Kura Hut',
               'Hope Arm Hut',
               'Hopeless Hut',
               'Horace Walker Hut',
               'Horseshoe Flat Hut',
               'Howletts Hut',
               'Hunters Hut',
               'Hunters Hut',
               'Hunts Creek Hut',
               'Hurricane Hut',
               'Hurunui Hut',
               'Hurunui No. 3 Hut',
               'Huxley Forks Hut',
               'Ida Railway Hut',
               'Ikawatea Forks Hut',
               'Iron Bark Hut',
               'Iron Gate Hut',
               'Island Gully Hut',
               'Isolation Hut',
               'Jam Hut',
               'John Reid Hut',
               'Jolliebrook Hut',
               'Jubilee Hut',
               'Julia Hut',
               'Junction Burn Hut',
               'Junction Hut',
               'Kahui Hut',
               'Kahunui Hut',
               'Kahurangi Keepers house',
               'Kapakapanui Hut',
               'Karamea Bend Hut',
               'Kawakawa Hut',
               'Kelly Knight Hut',
               'Kennedy Memorial Hut',
               'Kime Hut',
               'Kings Creek Hut',
               'Kintail Hut',
               'Kiritaki Hut',
               'Kirtle Burn Hut',
               'Kiwi Burn Hut',
               'Kiwi Hut – West Coast',
               'Kiwi Mouth Hut',
               'Kiwi Saddle Hut',
               'Kiwi Saddle Hut',
               'Koaunui Hut',
               'Komata Hut',
               'Koranga Forks Hut',
               'Kotepato Hut',
               'Kowhai Hut',
               'Lake Alexander Hut',
               'Lake Chalice Hut',
               'Lake Christabel Hut',
               'Lake Guyon Hut',
               'Lake Hankinson Hut',
               'Lake Matiri Hut',
               'Lake McRae Hut',
               'Lake Poteriteri Hut',
               'Lake Roe Hut',
               'Lake Thomson Hut',
               'Lame Duck Hut',
               'Larrikin Creek Hut',
               'Lawrence Hut',
               'Lees Creek Hut',
               'Leitch''s Hut',
               'Leon Kinvig Hut',
               'Liebig Hut',
               'Limestone Hut',
               'Loch Maree Hut',
               'Lochinvar Hut',
               'Locke Stream Hut',
               'Long Harry Hut',
               'Lower Arahura Hut',
               'Lower Goulter Hut',
               'Lower Princhester Hut',
               'Lupton Hut',
               'Mackintosh Hut',
               'Magdalen Hut',
               'Maitland Hut',
               'Makahu Saddle Hut',
               'Makakoere Hut',
               'Makaretu Hut',
               'Makarora Hut',
               'Makino Hut',
               'Makomako Hut',
               'Manaohou Right Branch Hut',
               'Mangahao Flats Hut',
               'Mangakahika Hut',
               'Mangamako Hut',
               'Mangamate Hut',
               'Mangapouri Hut',
               'Mangatainoka Hut',
               'Mangatoatoa Hut',
               'Mangatoetoe Hut',
               'Mangaturutu Hut',
               'Manson Hut',
               'Manuoha Hut',
               'Maori Saddle Hut',
               'Maropea Forks Hut',
               'Mason Bay Hut',
               'Maungahuka Hut',
               'McConchies Hut',
               'McCoy Hut',
               'McIntyre Hut',
               'McKerrow Island Hut',
               'McKinnon Hut',
               'Meg Hut',
               'Mid Goulter Hut',
               'Mid Pohangina Hut',
               'Mid Robinson Hut',
               'Mid Silverstream Hut',
               'Mid Taipo Hut',
               'Mid Waiohine Hut',
               'Mid Wairoa Hut',
               'Middle Gorge Hut',
               'Middle Hill Hut',
               'Middy Creek Hut',
               'Mikonui Flat Hut',
               'Mistake Flat Hut',
               'Mitre Flats Hut',
               'Moerangi Hut',
               'Mole Hut',
               'Monowai Hut',
               'Montgomerie Hut',
               'Monument Hut',
               'Morgan Hut',
               'Mt Fell Hut',
               'Mt Fyffe Hut',
               'Mt Rintoul Hut',
               'Mudflats Hut',
               'Neave Hut',
               'Neill Forks Hut',
               'Ngaawapurua Hut',
               'Ngahiramai Hut',
               'Ngamoko Hut',
               'Nichols Hut',
               'Nikau Flat Hut',
               'Nina Hut',
               'Oamaru Hut',
               'Ohane Hut',
               'Ohora Hut',
               'Okui Hut',
               'Old Man Hut',
               'Old Woman Hut',
               'Olivine Hut',
               'One Horn Hut',
               'Onepu Hut',
               'Oronui Hut',
               'Otamatapaio Hut',
               'Otapukawa Hut',
               'Otehake Hut',
               'Otukota Hut',
               'Otutu Hut',
               'Pāhautea Hut',
               'Pakihi Hut',
               'Pakituhi Hut',
               'Palmer Hut',
               'Pararaki Hut',
               'Parawai Lodge',
               'Parks Peak Hut',
               'Paske Hut',
               'Penk Hut',
               'Penn Creek Hut',
               'Philip J Cox Memorial Hut',
               'Pinchgut Hut',
               'Poet Hut',
               'Porters Creek Hut',
               'Poulter Hut',
               'Pourangaki Hut',
               'Price Flat Hut',
               'Purity Hut',
               'Puteore Hut',
               'Rakeahua Hut',
               'Rapid Creek Hut',
               'Red Hills Hut',
               'Red Hut',
               'Richmond Saddle Hut',
               'Roaring Stag Hut',
               'Rocks Ahead Hut',
               'Rocks Hut',
               'Rodger Inlet Hut',
               'Roebuck Hut',
               'Rogers Hut (Te Wairoa)',
               'Roses Hut',
               'Ruahine Corner Hut',
               'Ruahine Hut',
               'Saxton Hut',
               'Sayer Hut',
               'Scone Hut',
               'Sedgemere Sleepout',
               'Sentry Box Hut (historic)',
               'Severn Hut',
               'Shallow Bay Hut',
               'Shamrock Hut',
               'Shutes Hut',
               'Siberia Hut',
               'Skips Hut (Whangatawhia)',
               'Slaty Hut',
               'Smiths Stream Hut',
               'Smyth Hut',
               'Snowgrass Hut',
               'South Ohau Hut',
               'South Opuha Hut',
               'South Temple Hut',
               'St Jacob''s Hut',
               'Stafford Hut',
               'Stan''s Hut',
               'Stanfield Hut',
               'Starveall Hut',
               'Stone Hut',
               'Studholme Saddle Hut',
               'Supper Cove Hut',
               'Sutherlands Hut',
               'Syme Hut',
               'Tahupo Hut',
               'Tailings Hut',
               'Taipo Hut',
               'Taipo Hut',
               'Takarua Hut',
               'Tangihua Hut',
               'Tarn Hut',
               'Tarn Ridge Hut',
               'Tataweka Hut',
               'Tauanui Hut',
               'Taurawharona Hut',
               'Tawa Hut',
               'Tawhiwhi Hut',
               'Te Ekaou Hut',
               'Te Matawai Hut',
               'Te Panaa Hut',
               'Te Pourewa Hut',
               'Te Pua Hut',
               'Te Pukeohikarua (Te Puke) Hut',
               'Te Rangaakapua Hut',
               'Te Totara Hut',
               'Te Waiotukapiti Hut',
               'Te Waiti Hut',
               'Teal Bay Hut',
               'Thomas River Hut',
               'Three Mile Stream Hut',
               'Tiraumea Hut',
               'Top Butler Hut',
               'Top Dingle Hut',
               'Top Gordon Hut',
               'Top Hut – Otago',
               'Top Leatham Hut',
               'Top Misery Hut',
               'Top Robinson Hut',
               'Top Timaru Hut',
               'Top Toaroha Hut',
               'Top Wairoa Hut',
               'Trains Hut',
               'Trevor Carter Hut',
               'Triangle Hut',
               'Trilobite Hut',
               'Triplex Hut',
               'Trust/Poulter Hut',
               'Tussock Hut',
               'Tutaekuri Hut',
               'Tutuwai Hut',
               'Upper Gridiron Hut',
               'Upper Makaroro Hut',
               'Upper Spey Hut',
               'Upper Te Hoe Hut',
               'Upper Whirinaki Hut',
               'Venison Tops Hut (Tira Lodge)',
               'Venus Hut',
               'Waiau Hut',
               'Waiawa Hut',
               'Waihāhā Hut',
               'Waikamaka Hut',
               'Waikare Junction Hut',
               'Wainui Hut',
               'Waiopehu Hut',
               'Waipakihi Hut',
               'Waipawa Forks Hut',
               'Wairaurahiri Hut',
               'Waitewaewae Hut',
               'Waitutu Hut',
               'Wakelings Hut',
               'Warden Hut',
               'Washpool Hut',
               'Watchdog Hut',
               'Waterfall Hut',
               'West Arm Hut',
               'Whakatakaa Hut',
               'Wharfedale Hut',
               'Whymper Hut',
               'Wills Hut',
               'Worsley Hut',
               'Yankee River Hut',
               'Youngman Stream Hut',
               'Zekes Hut',
               'Zoo Hut'
    );

COMMIT;