SET ROLE = 'hut-finder';
BEGIN;

UPDATE hut
SET category = 5
WHERE name IN (
               'A Frame Hut',
               'Abrahams Bay Hunters Hut',
               'Adelaide Tarn Hut',
               'Adventure Bivvy',
               'Anderson''s Hut',
               'Ant Stream Bivvy',
               'Ant Stream Hut',
               'Aokaparangi Hut',
               'Aparima Forks Hut',
               'Apiti Hut',
               'Aranga Hut',
               'Archie''s Hut - Copper Creek',
               'Arete Hut',
               'Army Hut',
               'Asbestos Cottage',
               'Ashton Hut',
               'Avoca Hut',
               'Awatere Hut',
               'Back Basins Hide',
               'Back Ridge Bivouac',
               'Back Valley Hut',
               'Baikie Hut',
               'Ballarat Hut - Flood Burn',
               'Bealey Hut',
               'Bealey Spur Hut',
               'Becketts Hut',
               'Beech Hut',
               'Beetham Hut',
               'Benmore Hut',
               'Big Hopwood Burn Hut',
               'Black Birch Bivouac',
               'Black Birch Bivvy',
               'Bob''s Camp Bivvy',
               'Boo Boo Hut',
               'Borland Bivvy',
               'Boundary Creek Hut',
               'Boundary Hut',
               'Branch Bivvy',
               'Brass Monkey Bivvy',
               'Broken River Hut',
               'Brown Hut',
               'Browning Range Bivvy',
               'Bull Creek Hut',
               'Bull Flat Hut',
               'Bull Paddock Creek Hut',
               'Burn Creek Hut',
               'Burn Hut',
               'Buster Hut',
               'Cameron Hut',
               'Camerons Hut',
               'Camp Creek Hut',
               'Camp Stream Hut',
               'Campbell Bivvy',
               'Candlesticks Bivvy',
               'Canyon Creek Bivvy',
               'Carlyle Hut',
               'Carney''s Bivvy No. 1',
               'Carney''s Bivvy No. 2',
               'Caroline Hut',
               'Casino Hut',
               'Cass Saddle Hut',
               'Caswell Sound Hut',
               'Cavalier Hunters Hut',
               'Cecil Kings Hut',
               'Chaffey Hut',
               'Chew Tobacco Hunters Hut',
               'Chimney Creek Hut',
               'Christmas Village Hunters Hut',
               'Christopher (Ada) Cullers Hut',
               'Clark Hut',
               'Clark Hut - A Frame',
               'Cobb Hut',
               'Comyns Hut',
               'Cone Creek Hut',
               'Cone Hut',
               'Cookies Hut',
               'Copland Shelter',
               'County Stream Hut',
               'Cowshed Hut',
               'Crawford Junction Hut',
               'Creswicke Flat Hut',
               'Cromel Base Hut',
               'Cromel Branch Hut',
               'Crooked Spur Hut',
               'Crystal Bivvy',
               'Crystal Hut',
               'Dasler Biv',
               'Deep Creek Hut',
               'Devils Den Bivvy',
               'Dianes Hut',
               'Dickie Spur Hut',
               'Dillons Homestead Hut',
               'Dog Kennel Bivvy',
               'Dom Burn Sod Hut',
               'Dominie Hut',
               'Double Hut',
               'Doubtful Hut',
               'Downies Hut',
               'Dracophyllum Hut',
               'Dubious Bivvy',
               'Duckville Hut',
               'Dunns Creek Hut',
               'Dynamo Red Hut',
               'Eade Memorial Hut',
               'Earnslaw Hut',
               'East Hawdon Bivvy',
               'Eel Creek Hut',
               'Ellis Hut',
               'Erceg Hut',
               'Esk Bivvy',
               'Esquilant Bivvy Hut',
               'Evangeline Bivvy',
               'Evans Hut',
               'Explorer Hut',
               'Fidgit Bivvy',
               'Flora Hut',
               'Forbes Bivvy',
               'Forks Hut',
               'Frew Saddle Bivvy',
               'Frisco Hut',
               'Gabriel Hut',
               'Garston Ski Hut',
               'Gerhardt Spur Bivvy',
               'Glenrae Hut',
               'Goat Creek Hut',
               'Gold Creek Hut',
               'Gosling Hut',
               'Green Point Hut',
               'Greys Hut',
               'Griffin Creek Hut',
               'Grough Hut',
               'Happy Daze Hut',
               'Hapuatuna Hunters Hut',
               'Harper Pass Bivvy',
               'Haycocks Bivvy',
               'Healey Creek Hut',
               'Heather Jock Hut',
               'Herricks Hut',
               'Hideaway Hut',
               'Historic Cedar Flat Hut',
               'Historic Price Flat Hut',
               'History of Manson Hut',
               'Holyoakes Shelter',
               'Home Hill Hut',
               'Homestead Hunters Hut',
               'Hope Halfway Hut',
               'Hornby Bivvy',
               'Hurunui Hut',
               'Hut Creek Hut',
               'Iron Whare',
               'Irthing Hut',
               'Islands Hut',
               'Ivory Lake Hut',
               'Jacko Flat Hut',
               'Jervois Hut',
               'Jim''s Flat Hut',
               'Johnson Hut',
               'Jollie Hut',
               'Julia Hut (old)',
               'Kahutara Bivvy',
               'Kaipo Hut',
               'Kākāpō Hut',
               'Kanohirua Hut',
               'Kauritatahi Hut',
               'Kaweka Flats Bivvy',
               'Kay Creek Hut',
               'Kellys Hunters Hut',
               'Kiwi Flat Hut',
               'Koropuku Hut',
               'Kylie Bivvy',
               'Lagoon Saddle A Frame Hut',
               'Lagoon Saddle Hut',
               'Lake Man Bivvy',
               'Lake Morgan Hut',
               'Lake Stream Hut',
               'Landing Shed',
               'Lauder Basin Hut',
               'Lauper Biv',
               'Lawrence Bivvy',
               'Lincoln Hut',
               'Little Glory Hunters Hut',
               'Little Hellfire Hunters Hut',
               'Little Wanganui Gorge Shelter',
               'Lonely Lake Hut',
               'Lost Stream Bivvy',
               'Lower Olderog Bivvy',
               'Lower Salmon Creek Bivvy',
               'Lower Wairaki Hut',
               'Lower Windley Hut',
               'Lucretia Hut',
               'Lyell Hut',
               'Mackenzie Bivvy (East branch)',
               'Mackenzie Hut',
               'Maclennan Hut',
               'Mangakirikiri Hut',
               'Mangamuka Hut',
               'Manganuku Hut',
               'Mangaotane Hut (McMillans)',
               'Mansion Hut',
               'Manson Bivvy',
               'Manuka Hut',
               'Martin''s Hut',
               'Martins Creek Hunters Hut',
               'Mathias Hut',
               'McGregor Bivvy',
               'McIntosh Hut',
               'Mid King Bivvy',
               'Mid Styx Hut',
               'Mid Trent Hut',
               'Middle Head Hut',
               'Mikonui Spur Bivvy',
               'Minchin Bivvy',
               'Mingha Bivvy',
               'Ministry of Works Historic Hut',
               'Moa Stream Hut',
               'Mōkihinui Forks Hut',
               'Moonbeam Hut',
               'Moonlight and Roses Hut',
               'Motutapere Hut',
               'Mount Misery Hut',
               'Mt Bee Bunkrooms',
               'Mt Brown Hut',
               'Mt Curtis Hut',
               'Mt Sunday Bivvy',
               'Mullins Hut',
               'Mungo Hut',
               'Murphy''s Bivvy',
               'Murray Hunters Hut',
               'Myttons Hut',
               'Nardoo Hut',
               'Newton Creek Hut',
               'Newton Range Bivvy',
               'Nicholsons Hut',
               'Nolans Hut',
               'North Big Glory Hunters Hut',
               'North Borland Hut',
               'North Esk Hut (dilapidated)',
               'North Mangahao Bivvy',
               'North Ohau Hut',
               'North Pegasus Hunters Hut',
               'North Tikotatahi Hunters Hut',
               'North Whetu Bivvy',
               'Officers Hut',
               'Old Basins Hut',
               'Omaka Bivvy',
               'Omarukokere Bivvy',
               'Onslow Hut (Steffan Memorial Hut)',
               'Oreti Hut',
               'Otane Hut',
               'Otanetea Hut',
               'Palmer Bivvy',
               'Pearson Hut',
               'Pell Stream Hut',
               'Pfeifer Bivvy',
               'Pinnacle Bivvy',
               'Piripiri Hut',
               'Polluck Creek Hut',
               'Pool Hut',
               'Poor Pete''s Hut',
               'Port Adventure Hunters Hut',
               'Potts Hut',
               'Poulter Bivvy',
               'Poutaki Hut',
               'Price Basin Hut',
               'Puketeraki Bivvy',
               'Racemans Hut',
               'Ranger Bivvy',
               'Reardon Hut',
               'Red Stag Hut',
               'Redcliff Hut',
               'Reischek Hut',
               'Renata Hut',
               'Rerekapa Hut',
               'Riordans Hut',
               'Roaring Billy Hut',
               'Roaring Lion Hut',
               'Rocks Ahead Bivouac',
               'Rockslide Hut',
               'Rocky Creek Hut',
               'Rodger Inlet Hut (historic)',
               'Rokeby Hut',
               'Royal Hut',
               'Sawyer Burn Hut',
               'Scamper Torrent Hut',
               'Scotties Hut',
               'Scottys Bivvy',
               'Sefton Bivouac',
               'Serpentine Hut',
               'Shepherd Creek Hut',
               'Silverstream Bivvy',
               'Sir Robert Hut',
               'Slaty Creek Hut',
               'Slaughterburn Hut',
               'Slip Flat Hut',
               'Smoky Hunters Hut',
               'Snowy Gorge Hut',
               'Soper Shelter',
               'South Huxley Bivvy',
               'South Pegasus Hunters Hut',
               'Southwest Arm Hunters Hut',
               'Sparrowhawk Bivvy',
               'Spence Hut',
               'Splugeons Rock Shelter',
               'Spoon / Morgans Hut',
               'Spurs Hut',
               'St Winifreds Hut',
               'Stag Flat Shelter',
               'Staircase Hut',
               'Stanley Vale Hut',
               'Steele Creek Hut',
               'Steyning Hut',
               'Stodys Hut',
               'Stone Hut',
               'Stoney Creek Hut',
               'Stony Stream Bivvy',
               'Sudden Valley Bivvy',
               'Tarn Bivvy',
               'Tarn Hut',
               'Taruarau Bivvy',
               'Tautuku Hut',
               'Te Oneroa A-frame Hut',
               'Telford Hut',
               'Ten Man Hut',
               'Tent Camp',
               'The Gut Hut',
               'Thor Hut',
               'Toaroha Saddle Bivvy',
               'Toka Bivvy',
               'Top Crawford Hut',
               'Top Crooked Hut',
               'Top Gorge Hut',
               'Top Hope Hut',
               'Top Hut',
               'Top Hut',
               'Top Kokatahi Hut',
               'Top Maropea Hut',
               'Top Olderog Bivvy',
               'Top Trent Hut/Lagoon Hut',
               'Top Tuke Hut',
               'Top Waitaha Hut',
               'Top Waitahu Bivvy',
               'Townsend Hut',
               'Traverse (A-Frame) Hut',
               'Tribulation Hut',
               'Tunnel Creek Hut',
               'Turkeys Nest Bivvy',
               'Turnbull Bivvy',
               'Turnbull''s (Big Dam) Hut',
               'Tutu Hut',
               'Two Mile Hut',
               'Unknown Stream Hut',
               'Upper Cromel Hut',
               'Upper D''Urville Hut',
               'Upper Deception Hut',
               'Upper Lords Hunters Hut',
               'Upper Matakuhia Hut',
               'Upper Nina Bivvy',
               'Upper Oreti Hut',
               'Upper Princhester Hut',
               'Upper South Branch Hurunui Hut',
               'Upper Wairaki Hut',
               'Upper Windley Hut',
               'Urquhart''s Hut',
               'Veil Biv',
               'Waihua Hut',
               'Waikiti Hut',
               'Waikokopu Hut',
               'Waimakariri Falls Hut',
               'Waingaro Forks Hut',
               'Waiorongomai Hut',
               'Waiotauru Hut',
               'Wallers Hut',
               'Wānaka Faces Hut',
               'Weka Burnet Bivvy',
               'West Burn Hut',
               'West Harper Hut',
               'West Mathias Bivvy',
               'Westies Hut',
               'Whangaehu Hut',
               'Whare Creek Hut',
               'Wharekahika Hut',
               'Wharepapa Hut',
               'Wheel Creek Hut',
               'Wildlife Hut',
               'Wilkinson Hut',
               'Winchcombe Biv',
               'Wire Yards Hut',
               'Worsley Bivvy',
               'Yeats Ridge Hut'
    );

COMMIT;