services:
  utilities:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    build:
      context: hut-finder-utilities
    ports:
      - 5432:5432

  api:
    environment:
      DB_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host.docker.internal:5432/${POSTGRES_DB}"
      PORT: ${API_PORT}
    build:
      context: hut-finder-api
      target: runtime
    depends_on:
      utilities:
        condition: service_healthy
    ports:
      - ${API_PORT}:${API_PORT}