[package]
name = "hut-finder-utilities"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
csv = "1.3.1"
serde = { version = "1.0.215", features = ["derive"] }
rpassword = "7.3.1"
postgres = "0.19.9"